### ISSUE TITLE
User Registration and Data Management

### ISSUE THREAD

**Issue by black-iverson123** [crazycoder44/CBE---Result-Management-Portal#1]
Hey bro,

Love what your project is about and I think this is awesome, But its kinda tedious to manually enter data into the created table. I would like to contribute to this project, have an idea that would work with your database.

**Comment by crazycoder44** [comment]
Thanks bro. I really appreciate your feedback. Please feel free to make your contributions anytime.

**Comment by black-iverson123** [comment]
Noted
